from pathlib import Path

import pytest

from text_to_sql_agent.config import Settings
from text_to_sql_agent.database import POSTGRES_SCHEMA, get_database_dialect


def test_settings_detects_sqlite_database_source(tmp_path: Path) -> None:
    database_path = tmp_path / "sample.db"
    settings = Settings(DATABASE_URL=f"sqlite:///{database_path}")

    assert settings.database_dialect == "sqlite"
    assert settings.database_source == database_path


def test_settings_detects_postgres_database_source() -> None:
    settings = Settings(DATABASE_URL="postgresql://user:pass@localhost:5432/app")

    assert settings.database_dialect == "postgresql"
    assert settings.database_source == "postgresql://user:pass@localhost:5432/app"
    with pytest.raises(ValueError, match="Only sqlite"):
        _ = settings.database_path


def test_database_dialect_accepts_postgres_url_alias() -> None:
    assert get_database_dialect("postgres://user:pass@localhost:5432/app") == "postgresql"


def test_database_dialect_rejects_unsupported_url() -> None:
    with pytest.raises(ValueError, match="SQLite path/URL or PostgreSQL URL"):
        get_database_dialect("mysql://user:pass@localhost/app")


def test_postgres_schema_uses_identity_columns() -> None:
    assert "AUTOINCREMENT" not in POSTGRES_SCHEMA
    assert "GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" in POSTGRES_SCHEMA
